# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Clustering"); Pkg.test("Clustering"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Clustering")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
